// <auto-generated />
using JobPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace JobPortal.Migrations.JobSeekerDb
{
    [DbContext(typeof(JobSeekerDbContext))]
    [Migration("20180418181944_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("JobPortal.Models.JobSeekerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountType");

                    b.Property<string>("Achivements");

                    b.Property<string>("AppliedJobs");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired();

                    b.Property<string>("CurrentLocation");

                    b.Property<string>("EmailID")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("HighestQualification");

                    b.Property<string>("HighestQualificationCollege");

                    b.Property<DateTime>("HighestQualificationCompletionTime");

                    b.Property<DateTime>("HighestQualificationStartingTime");

                    b.Property<string>("HighestQualificationSubject");

                    b.Property<string>("Industry");

                    b.Property<string>("JobLocation");

                    b.Property<string>("JobRole");

                    b.Property<string>("KeySkills");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("LinkedInLink");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("ResumeLink");

                    b.Property<string>("ShortBio");

                    b.Property<string>("TotalExperience");

                    b.Property<string>("WebsiteLink");

                    b.HasKey("ID");

                    b.ToTable("JobSeekers");
                });
#pragma warning restore 612, 618
        }
    }
}
