// <auto-generated />
using JobPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace JobPortal.Migrations.RecruiterDb
{
    [DbContext(typeof(RecruiterDbContext))]
    partial class RecruiterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("JobPortal.Models.RecruiterModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountType");

                    b.Property<string>("Achivements");

                    b.Property<string>("CompanyAddress");

                    b.Property<string>("CompanyCountry");

                    b.Property<string>("CompanyName");

                    b.Property<string>("CompanyState");

                    b.Property<string>("CompanywebsiteLink");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired();

                    b.Property<string>("CurrentDesignation");

                    b.Property<string>("CurrentLocation");

                    b.Property<string>("EmailID")
                        .IsRequired();

                    b.Property<string>("ExperienceInHiring");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Industry");

                    b.Property<string>("JobsPosted");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("NumberOfEmployees");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Recruiters");
                });
#pragma warning restore 612, 618
        }
    }
}
